package com.helpyou.model;

import java.util.Date;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.UserID
     *
     * @mbg.generated Sat Nov 11 22:18:23 CST 2017
     */
    private String userID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.UserName
     *
     * @mbg.generated Sat Nov 11 22:18:23 CST 2017
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.WechatID
     *
     * @mbg.generated Sat Nov 11 22:18:23 CST 2017
     */
    private String wechatID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.Pwd
     *
     * @mbg.generated Sat Nov 11 22:18:23 CST 2017
     */
    private String pwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.QQ
     *
     * @mbg.generated Sat Nov 11 22:18:23 CST 2017
     */
    private String QQ;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.Deleteflg
     *
     * @mbg.generated Sat Nov 11 22:18:23 CST 2017
     */
    private Boolean deleteflg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.CreateTime
     *
     * @mbg.generated Sat Nov 11 22:18:23 CST 2017
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table User
     *
     * @mbg.generated Sat Nov 11 22:18:23 CST 2017
     */
    public User(String userID, String userName, String wechatID, String pwd, String QQ, Boolean deleteflg, Date createTime) {
        this.userID = userID;
        this.userName = userName;
        this.wechatID = wechatID;
        this.pwd = pwd;
        this.QQ = QQ;
        this.deleteflg = deleteflg;
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table User
     *
     * @mbg.generated Sat Nov 11 22:18:23 CST 2017
     */
    public User() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.UserID
     *
     * @return the value of User.UserID
     *
     * @mbg.generated Sat Nov 11 22:18:23 CST 2017
     */
    public String getUserID() {
        return userID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.UserID
     *
     * @param userID the value for User.UserID
     *
     * @mbg.generated Sat Nov 11 22:18:23 CST 2017
     */
    public void setUserID(String userID) {
        this.userID = userID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.UserName
     *
     * @return the value of User.UserName
     *
     * @mbg.generated Sat Nov 11 22:18:23 CST 2017
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.UserName
     *
     * @param userName the value for User.UserName
     *
     * @mbg.generated Sat Nov 11 22:18:23 CST 2017
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.WechatID
     *
     * @return the value of User.WechatID
     *
     * @mbg.generated Sat Nov 11 22:18:23 CST 2017
     */
    public String getWechatID() {
        return wechatID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.WechatID
     *
     * @param wechatID the value for User.WechatID
     *
     * @mbg.generated Sat Nov 11 22:18:23 CST 2017
     */
    public void setWechatID(String wechatID) {
        this.wechatID = wechatID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.Pwd
     *
     * @return the value of User.Pwd
     *
     * @mbg.generated Sat Nov 11 22:18:23 CST 2017
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.Pwd
     *
     * @param pwd the value for User.Pwd
     *
     * @mbg.generated Sat Nov 11 22:18:23 CST 2017
     */
    public void setPwd(String pwd) {
        this.pwd = pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.QQ
     *
     * @return the value of User.QQ
     *
     * @mbg.generated Sat Nov 11 22:18:23 CST 2017
     */
    public String getQQ() {
        return QQ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.QQ
     *
     * @param QQ the value for User.QQ
     *
     * @mbg.generated Sat Nov 11 22:18:23 CST 2017
     */
    public void setQQ(String QQ) {
        this.QQ = QQ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.Deleteflg
     *
     * @return the value of User.Deleteflg
     *
     * @mbg.generated Sat Nov 11 22:18:23 CST 2017
     */
    public Boolean getDeleteflg() {
        return deleteflg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.Deleteflg
     *
     * @param deleteflg the value for User.Deleteflg
     *
     * @mbg.generated Sat Nov 11 22:18:23 CST 2017
     */
    public void setDeleteflg(Boolean deleteflg) {
        this.deleteflg = deleteflg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.CreateTime
     *
     * @return the value of User.CreateTime
     *
     * @mbg.generated Sat Nov 11 22:18:23 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.CreateTime
     *
     * @param createTime the value for User.CreateTime
     *
     * @mbg.generated Sat Nov 11 22:18:23 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}